[package]
name = "system-register-protocol"
version = "0.1.0"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]

[dependencies]


[target.'cfg(windows)'.dependencies]
winreg = '0.4.0'

[dev-dependencies]
rand = "0.3.0"