[package]
name = "system-register-protocol"
version = "0.1.0"
authors = ["Benjamin Kampmann <ben@gnunicorn.org>"]

[dependencies]

[dev-dependencies]
rand = "0.3.0"


[target.'cfg(windows)'.dependencies]
winreg = '0.4.0'

[target.'cfg(macos)'.dependencies]
libc  = "0.2"
objc = "0.2"